baseurl: 'https://example.com/'
languageCode: cs-CZ
title: jameshruby blog
theme: hyde-hyde

summarylength: 30
paginate: 3
enableEmoji: true
enableRobotsTXT: true

params:
  author: jameshruby
  title: jameshruby blog
  description: ''
  keywords: 'jameshruby, blog'
  authorimage: /img/wolfProfile.png
  favicon: /img/wolfProfile.png
  dateformat: '01/02/2006'
  themeColor : 'theme-base-j-vs'  
  relatedPosts: false

  # social:
      # github: <username>
      # email: your-email@example.com
menu:
  main:
    - name: Posts
      weight: 100
      identifier: posts
      url: /posts/
    - name: About
      identifier: about
      weight: 300
      url: /about/
    - name: Contact
      identifier: contact
      weight: 400
      url: /contact/