baseurl: 'https://jameshruby.github.io/'
languageCode: cs-CZ
title: jameshruby blog
theme: hyde-hyde

summarylength: 30
paginate: 7
enableEmoji: true
enableRobotsTXT: true

permalinks:
  posts: '/:title/'
#     posts: '/:year/:month/:slug/'
#     posts: '/:year/:month/:title/'
   
params:
  author: jameshruby
  title: jameshruby blog
  description: ''  # „Umění není nikdy hotové, pouze odložené“ - Da Vinci
  keywords: 'jameshruby, blog'
  authorimage: /img/penquinProfile.jpg
  favicon: /img/penquinProfile.jpg
  dateformat: '01/02/2006'
  themeColor : 'theme-base-j-vs'
  relatedPosts: false
  postNavigation: false

  # social:
      # github: <username>
      # email: your-email@example.com
menu:
  main:
    - name: Domů
      weight: 1
      identifier: home
      url: /
    - name: Kategorie
      weight: 100
      identifier: categories
      url: /categories
#    - name: Příspěvky
#      weight: 100
#      identifier: posts
#      url: /posts/
#    - name: About
#      identifier: about
#      weight: 300
#      url: /about/
#    - name: Contact
#      identifier: contact
#      weight: 400
#      url: /contact/