baseurl: 'https://example.com/'
languageCode: cs-CZ
title: jameshruby blog
theme: hyde-hyde

summarylength: 30
paginate: 3

params:
  author: jameshruby
  title: jameshruby blog
  authorimage: /img/wolfProfile.png
  dateformat: '01/02/2006'
  themeColor : 'theme-base-j-vs'  

social:
    # github: <username>
    # email: your-email@example.com
menu:
  main:
    - name: Posts
      weight: 100
      identifier: posts
      url: /posts/
    - name: About
      identifier: about
      weight: 300
      url: /about/